services:
  # --- SERVIDOR WEB (Apache + PHP) ---
  webserver:
    build: .
    container_name: mi_servidor_web
    ports:
      - "8080:80"  # Mapeamos el puerto 8080 de tu Mac al 80 del contenedor
    volumes:
      - ./www:/var/www/html # Tu carpeta local se sincroniza con el contenedor
    depends_on:
      - db
    networks:
      - lamp-network

  # --- BASE DE DATOS (MySQL) ---
  db:
    image: mysql:8.0
    container_name: MySQL
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # Contraseña maestra
      MYSQL_DATABASE: mi_proyecto
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos (para no perderlos al apagar)
    networks:
      - lamp-network

  # --- GESTOR VISUAL (phpMyAdmin) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lamp-network

# Definición de volúmenes y redes
volumes:
  db_data:

networks:
  lamp-network: